[server]
# Increase max upload size to ~1 GB (adjust as needed)
maxUploadSize = 1024

[theme]
primaryColor="#7C3AED"
backgroundColor="#0B0F19"
secondaryBackgroundColor="#111827"
textColor="#E5E7EB"
font="sans serif"