# Copy these values into your deployment's secret manager or local .streamlit/secrets.toml
# Do NOT commit real credentials to source control.

[smtp]
# SMTP relay settings (example below for SendGrid). You can use any SMTP provider.
host = "smtp.sendgrid.net"
port = 587
user = "apikey"                         # For SendGrid, use the literal "apikey"
password = "SG.xxxxxxxx_your_api_key"   # Your SMTP/API key
from = "no-reply@example.com"           # The sender identity (must be verified on some providers)
to = "your-hidden-inbox@example.com"    # Where feedback gets delivered (kept secret via Streamlit secrets)
use_tls = true