# Copy these values into your deployment's secret manager or local .streamlit/secrets.toml
# Do NOT commit real credentials to source control.

[smtp]
# SMTP relay settings for sending feedback emails. Choose one of the examples below:

# ===== SendGrid Example =====
# Reliable email service with good deliverability
host = "smtp.sendgrid.net"
port = 587
user = "apikey"                         # For SendGrid, use the literal "apikey"
password = "SG.xxxxxxxx_your_api_key"   # Your SMTP/API key
from = "no-reply@example.com"           # The sender identity (must be verified on some providers)
to = "your-hidden-inbox@example.com"    # Where feedback gets delivered (kept secret via Streamlit secrets)
use_tls = true

# ===== Gmail Example =====
# Free option if you have a Gmail account. Requires App Password (not regular password).
# To set up: Google Account > Security > 2-Step Verification > App Passwords
# host = "smtp.gmail.com"
# port = 587
# user = "your-email@gmail.com"
# password = "your-16-character-app-password"  # Use App Password, NOT your regular Gmail password
# from = "your-email@gmail.com"
# to = "feedback-recipient@example.com"
# use_tls = true

# ===== Microsoft 365 / Outlook Example =====
# For business/enterprise Microsoft 365 accounts
# host = "smtp-mail.outlook.com"
# port = 587
# user = "your-email@yourcompany.com"
# password = "your-password"              # Regular password or app password
# from = "your-email@yourcompany.com"
# to = "feedback@yourcompany.com"
# use_tls = true

# ===== Advanced Options =====
# debug = true                           # Enable SMTP transcript for troubleshooting (optional)

# Port Guide:
# - 587: STARTTLS (most common, use with use_tls=true)
# - 465: SSL/TLS (use with use_tls=false) 
# - 25: Plain text (not recommended, use with use_tls=false)